name: Build My Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission
      run: chmod +x ./gradlew
    
    - name: Build AniGo extension (debug version - no signing needed)
      run: ./gradlew :anigo:assembleDebug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: anigo-debug-apk
        path: src/en/anigo/build/outputs/apk/debug/*.apk
        retention-days: 30
